### ISSUE TITLE
bug: decodeDeployData

### ISSUE THREAD

**Issue by AlexBHarley** [wagmi-dev/viem#855] opened 2023-07-07 10:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.10

### Current Behavior

I'm unable to decode the constructor data for the AccessControlledOffchainAggregator on Goerli. It's available here https://goerli.etherscan.io/address/0x9b0FC4bb9981e5333689d69BdBF66351B9861E62

### Expected Behavior

I should be able to decode all the constructor arguments.

### Steps To Reproduce

I've included a StackBlitz link with the relevant ABI, bytecode and input fields filled in.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-tfhb65?file=index.ts

**Comment by jxom** [comment] 2023-07-08 14:04
I noticed your input isn’t prefixed with `0x`, so that might be why! Let me know if it still doesn’t work after that.

**Comment by AlexBHarley** [comment] 2023-07-08 15:12
@jxom no, that doesn't fix it. The input can't be prefixed with `0x` as it's explicitly prefixed inside `decodeDeployData` https://github.com/wagmi-dev/viem/blob/main/src/utils/abi/decodeDeployData.ts#L45

**Comment by jxom** [comment] 2023-07-08 15:20
Ah that’s because the input also contains the bytecode (which needs to be `0x` prefixed). Will take a look when I’m at a computer.

**Comment by jxom** [comment] 2023-07-09 03:51
Just had a closer look. Seems like the `input` bytecode mismatches the `bytecode` provided.  Are you sure the `input` references the same deployment? I just did a sanity check and deployed a contract, and then decoded the deployment txn input, and it seems to work for me.

Going to close this for now, but we can keep the discussion going.

**Closed by jxom** 2023-07-09 03:51 UTC

**Comment by AlexBHarley** [comment] 2023-07-09 07:06
@jxom I've updated the Stackblitz link to fetch the necessary data (tx input, ABI, bytecode) from Etherscan and a public RPC  endpoint, so we can be reasonably sure the parameters are correct. 

I'm still running into the same problems unfortunately,

**Comment by jxom** [comment] 2023-07-09 07:10
How was the original bytecode generated? The deployment transactions `input` shouldn’t be different to the compiled contracts bytecode.

**Comment by jxom** [comment] 2023-07-09 07:11
Could be useful to add an end-to-end minimal reproducible example of deploying a contract, and decoding the deployment transaction.

**Comment by AlexBHarley** [comment] 2023-07-10 16:05
I've had no problems with `decodeDeployData` working on other contracts, this one though seemed buggy, hence raising the issue. For example, swapping the address to `0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45`,(the Uniswap V3 Router) decoding works just fine.

The exact error logged in that Stackblitz repro is `SliceOffsetOutOfBoundsError: Slice starting at offset "6.31180258764031e+76" is out-of-bounds (size: 23429).`

This contract in question here is the underlying aggregator for the Chainlink `ETH / USD` feed. I don't know how they deployed it but I assume it was in a reasonably standard manner.

**Comment by jxom** [comment] 2023-07-10 17:19
On line 71, the input shouldn’t be sliced. Does it work if you omit that? I’m not at a computer right now, so can’t check

**Comment by jxom** [comment] 2023-07-10 17:25
Can have a further look soon though!
