### ISSUE TITLE
How to get the privatekey after generate an account from mnemonicToAccount

### ISSUE THREAD

**Issue by francelwebdev** [wagmi-dev/viem#1501] opened 2023-11-15 16:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Anything else?

How to get the privatekey after generate an account from mnemonicToAccount

**Comment by tmm** [comment] 2023-11-15 17:19
Duplicate of https://github.com/wagmi-dev/viem/discussions/1487

**Closed by tmm** 2023-11-15 17:19 UTC
