### ISSUE TITLE
bug: simulateContract type error

### ISSUE THREAD

**Issue by ryeshrimp** [wagmi-dev/viem#339] opened 2023-04-07 20:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.12

### Current Behavior

![image](https://user-images.githubusercontent.com/99738501/230672181-6bf680e8-03b1-4871-9c21-7c220a2bce48.png)

> Type '`0x${string}`' is not assignable to type 'never'.ts(2322)

### Expected Behavior

Should not receive a type error

### Steps To Reproduce

```
const [address] = await walletClient.getAddresses();
const { request } = await publicClient.simulateContract({
    account: address,
    address: contract,
    abi: ERC721_ABI,
    functionName: 'setApprovalForAll',
    args: ['0x...', true],
  });
```

**Comment by tmm** [comment] 2023-04-07 21:22
Thanks for reporting! What version of TypeScript are you using? viem requires [TypeScript v4.9.4 or greater](https://viem.sh/docs/typescript.html).

Tried reproducing this issue in a [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wBQFcAjAG2DQGFzMA7GAGhXS10wHVtTTMZrg6jZmkIBnGBBBNUACxgww0uGGxRRmAILFgTAL5wAZlElwA5ADcBIU0iRoItcXADuXHnxr04AXhY48nNy8-IIAFAhwMFDYjpCwAFzoYhIgoc7AtAAmEM4AdLwymFiEIACEAJRwuuV2Dk5gJORUnvC+GP4EjRQh9OGR0bHQMIlyCqGV1bb2jvAA2tiZmViiogC6PnDYrsDwrkEeAvS5AOa8GovL6qLjtTOIcFgAjoSYTvq+W9g7yl3NhzC5USgQikNiUBxRbBoGDhZhQ+yEeiJBZLV6iJQAegxcAAegB+OEXNGJUwABgAHqYlNhtIkVGpNNpQrNmKhTAZEdDgA44OoYBowGBjOYuAAxaAabihFGXOAAfQgYCKuGgDDgxAgEFI8uwguFmEylUw5LwUFoXCpzFW5SUHNoXIcADlsCBMCS+QKhRARaRxVBJaRLahVMdRIlZmTKWqoi9VnoakA), but was unable. If you could provide a minimal reproducible example can look into this more.

**Comment by fubhy** [comment] 2023-04-09 12:07
Depending on your typescript version & configuration, this might be caused by you e.g. having sth. like `noUncheckedIndexedAccess` configured: https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

In this case, you'd have to first check that `address` is actually set (so, after destructuring the return value of `getAddresses`, you'd have to check if `address` is set:

```typescript
const [address] = await walletClient.getAddresses();
if (address === undefined) {
  throw new Error('Expected address');
}

const { request } = await publicClient.simulateContract({
    account: address,
    address: contract,
    abi: ERC721_ABI,
    functionName: 'setApprovalForAll',
    args: ['0x...', true],
  });
```

It's imposible to know the right answer to this question without seeing a reproduction of the problem as Tom already mentioned :)

**Comment by jxom** [comment] 2023-04-09 21:56
Going to close this. Will re-open when minimal reproduction is provided.

**Closed by jxom** 2023-04-09 21:56 UTC
Labels: needs reproduction

**Comment by ryeshrimp** [comment] 2023-04-10 15:52
Will try to post a reproducible when I get a chance. 

Re: @tmm - typescript is the latest version, so not the issue here
Re: @fubhy - address is assuming it's a `0x{string}`, it the fact that simulateContract for some reason things account is type never.

**Comment by DannyDelott** [comment] 2023-05-15 21:47
> Will try to post a reproducible when I get a chance.
> 
> Re: @tmm - typescript is the latest version, so not the issue here Re: @fubhy - address is assuming it's a `0x{string}`, it the fact that simulateContract for some reason things account is type never.

As a data point, I just encountered this and it turned out to be a monorepo thing. We use Turborepo and therefore have typescript listed in a few package.jsons. 

Turns out we had `typescript@^4.9.3` listed correctly in our app, but our top-level package.json was configured for `typescript@3.0.0`. Changed that, re-ran yarn, and everything worked 👍

**Comment by aniketbiprojit** [comment] 2023-07-28 09:08
Still facing this issue:

<img width="905" alt="image" src="https://github.com/wagmi-dev/viem/assets/24915107/ed8fcfa9-9f8c-4257-a0df-d2fe4eec245b">


```
{
		"typescript": "5.1.6",
		"viem": "^1.4.2",
		"wagmi": "^1.3.9",
}
```
