### ISSUE TITLE
bug: Request method eth_chainId is not supported Version: viem@0.3.37

### ISSUE THREAD

**Issue by BitMaster001** [wagmi-dev/viem#594] opened 2023-05-29 00:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.37

### Current Behavior

In my React project, I'm using wagmi and viem to integrate smart contract. Here is the code.

```
const { request } = await publicClient.simulateContract({
      ...wagmiConfig,
      functionName: "buyFromIPO",
      account,
      args: [BigInt(id), BigInt(amount)]
});
const hash = await walletClient.writeContract(request);
```
And got the following error message from console.
```
Request Arguments:
  chain:  Polygon Mumbai (id: 80001)
  from:   0x1c60bbdedd2fc55f64d3ffa5cdefa1c6ae24262a
  to:     0x47efDaB9801FFD9d7a74F899288cF01fb6ff0Bf0
  data:   0xc61a759e00000000000000000000000000000000000000000000000000000000000000430000000000000000000000000000000000000000000000000000000000000014

Details: Request method eth_chainId is not supported
Version: viem@0.3.37
    at getTransactionError (getTransactionError.js:7:1)
    at sendTransaction (sendTransaction.js:76:34)
    at async writeContract (writeContract.js:9:1)
```

### Expected Behavior

This shouldn't throw error.

### Steps To Reproduce

1. Create react app using typescript template.
2. Insert my code into action handler function.
3. Make a call

**Comment by jxom** [comment] 2023-05-29 02:01
Works for me: https://stackblitz.com/edit/github-wk9aah-ogd52l?file=index.tsx

Can you please fork that and reproduce it for me there? The RPC URL you are using might not support `eth_chainId`. Might be best to use a stable RPC Provider such as Ankr (https://rpc.ankr.com/polygon_mumbai). Closing until a reproduction is provided.

**Closed by jxom** 2023-05-29 02:01 UTC

**Comment by BitMaster001** [comment] 2023-05-29 18:06
Hi @jxom , I found the solution. Inside wallet connect handler, I must use `walletClient.requestAddresses()`. Before, I used `useConnect()` hook of `wagmi` package.
